### ISSUE TITLE
Babel build fails when url-search-params-polyfill is included

### ISSUE THREAD

**Issue by borekl** [jerrybendy/url-search-params-polyfill#43]
I am not sure if this is problem with the polyfill, but when I include it in babel.config.js, it causes the build to fail.

    module.exports = {
      presets: [
        ['@vue/app', {
          polyfills:
          [
            'url-search-params-polyfill'
          ]
        }]
      ]
    }

This results in quite cryptic failure I have problem understanding.

    ./src/main.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: [BABEL] /opt/ondb/dev-front/ondb-frontend/src/main.js: Cannot read property 'chrome' of undefined (While processing: "/opt/ondb/dev-front/ondb-frontend/node_modules/@vue/babel-preset-app/index.js")
        at targetEnvironments.filter.environment (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/preset-env/lib/index.js:75:16)
        at Array.filter (<anonymous>)
        at isPluginRequired (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/preset-env/lib/index.js:74:56)
        at includes.filter.item (/opt/ondb/dev-front/ondb-frontend/node_modules/@vue/babel-preset-app/index.js:26:12)
        at Array.filter (<anonymous>)
        at getPolyfills (/opt/ondb/dev-front/ondb-frontend/node_modules/@vue/babel-preset-app/index.js:25:19)
        at module.exports (/opt/ondb/dev-front/ondb-frontend/node_modules/@vue/babel-preset-app/index.js:106:17)
        at loadDescriptor (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/core/lib/config/full.js:165:14)
        at cachedFunction (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/core/lib/config/caching.js:33:19)
        at loadPresetDescriptor (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/core/lib/config/full.js:235:63)
        at config.presets.reduce (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/core/lib/config/full.js:77:21)
        at Array.reduce (<anonymous>)
        at recurseDescriptors (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/core/lib/config/full.js:74:38)
        at loadFullConfig (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/core/lib/config/full.js:108:6)
        at process.nextTick (/opt/ondb/dev-front/ondb-frontend/node_modules/@babel/core/lib/transform.js:28:33)
        at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by jerrybendy** [comment]
Hi,

This library is a polyfill of URLSearchParams only. You can use this with `import "url-search-params-polyfill"` in your `main.js`. This is not a plugin of babel or vue.

In vue CLI 3 project, it uses `core-js` to polyfill unsupported features. You can do `import 'core-js/features/url-search-params'` instead, so that you don't need this library.

**Comment by borekl** [comment]
Yes, you're right. I was under impression that babel simply includes whatever you list in its list of polyfills. Simply importing stuff in `main.js` works fine. Thank you for you patience.

**Comment by jerrybendy** [comment]
Your polyfill config is for `@vue/cli-plugin-babel` and the source code is in `@vue/babel-preset-app`. 

`@vue/babel-preset-app` uses `core-js@^2.6.5`, you can check `https://github.com/zloirock/core-js/tree/v2` to get all available options. But the latest version of `core-js@^2` doesn't support URLSearchParams.
