### ISSUE TITLE
Can't handle hasOwnProperty in search params

### ISSUE THREAD

**Issue by kyyyle** [jerrybendy/url-search-params-polyfill#47]
Using `v7.0.1`

Trying to parse a URL with `hasOwnProperty` as a search param (for example `http://mysite.com?hasOwnParam=abcde`) results in a `TypeError` with the following trace. This is case sensitive, so `hasownproperty=abcde` works fine.

I'm calling: `const params = URLSearchParams(searchString)`

This was caught by bugsnag, and we are not using this param anywhere. I suspect it's some kind of attempted code injection attack, or something of that sort.

```
TypeError: dict[name].push is not a function
    at appendTo (/code/enterprisepaxfe/node_modules/url-search-params-polyfill/index.js:326:24)
    at parseToDict (/code/enterprisepaxfe/node_modules/url-search-params-polyfill/index.js:307:21)
    at URLSearchParamsPolyfill (/code/enterprisepaxfe/node_modules/url-search-params-polyfill/index.js:44:38)
    at URLSearchParams (/code/enterprisepaxfe/.dist/server/webpack:/src/components/VsmRouteState/index.jsx:39:40)
    at Route.render (/code/enterprisepaxfe/node_modules/react-router/Route.js:124:32)
    at processChild (/code/enterprisepaxfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:2207:18)
    at resolve (/code/enterprisepaxfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:2064:5)
    at ReactDOMServerRenderer.render (/code/enterprisepaxfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:2349:22)
    at ReactDOMServerRenderer.read (/code/enterprisepaxfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:2323:19)
    at Object.renderToString (/code/enterprisepaxfe/node_modules/react-dom/cjs/react-dom-server.node.development.js:2695:25)
    at renderToString (/code/enterprisepaxfe/.dist/server/webpack:/src/server/renderBundle.jsx:56:30)
    at /code/enterprisepaxfe/.dist/server/webpack:/src/server/index.js:64:17
    at Layer.handle [as handle_request] (/code/enterprisepaxfe/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/code/enterprisepaxfe/node_modules/express/lib/router/index.js:317:13)
    at /code/enterprisepaxfe/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/code/enterprisepaxfe/node_modules/express/lib/router/index.js:335:12)
```

**Comment by jerrybendy** [comment]
Hi,

I got your point. I use `name in dict` to judge if a key in `dict` in my [code](https://github.com/jerrybendy/url-search-params-polyfill/blob/master/index.js#L325), it's not strict.  I should change `in` to `hasOwnProperty`.

```diff
- if (name in dict) {
+ if (dict.hasOwnProperty) {
```

**Comment by kyyyle** [comment]
Thanks for the quick turnaround!
